version: "3.9"

services:
  db:
    image: postgres:15
    container_name: demo_postgres
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demoapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: demo_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: demo
      DB_PASSWORD: demo
      DB_NAME: demoapp
    ports:
      - "3000:3000"

volumes:
  db_data: