version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: demoapp
    ports:
      - "5432:5432"

  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://demo:demo@db:5432/demoapp?sslmode=disable"
      PORT: 3000
    depends_on:
      - db
